### ISSUE TITLE
[RFT] Cannot read property 'getReadableValue' of undefined | ProgramEnrolment

### ISSUE THREAD

**Issue by arjunk** [avniproject/jnpct#117] opened 2024-04-09 07:34 UTC
source type : EnrolmentSummary
source id : `26d3e45e-7174-433f-b4a7-db1524648252`
entity type : ProgramEnrolment
Current count : 73

**Comment by BEULAHEVANJALIN** [comment] 2024-04-09 12:09
There is no way for programEnrolment.findLatestObservationInEntireEnrolment("Last menstrual period") to be undefined since it is a mandatory field.

Workaround:
- I logged in with the catchments of users who reported rule failures. When attempting to reproduce the error, I found there is no way to reach that error point.
- I tried logging the LMP date, and that date is not undefined as well.
- Most of the created_date_time's are before 2024-03-14, which seems this wasn't done earlier. So thought of clearing these failures to see if they come back. Ideally they should not!.
- Then i checked the sync times of those users and the latest rule failure time. It appears the rule failures occurred earlier. If these two times were the same, then we could conclude that the problem arises with every sync. As we see in the following query that the user was able to sync without any errors, there potentially can be no issue with future syncs as well.
```
with distinct_users as (select distinct created_by_id
                        from rule_failure_telemetry
                        where is_closed is false
                          and rule_uuid = '26d3e45e-7174-433f-b4a7-db1524648252'),
     latest_sync_time as (select user_id,
                                 created_date_time,
                                 row_number() over (partition by created_by_id order by created_date_time desc) as rn
                          from sync_telemetry
                          where user_id in (select created_by_id from distinct_users)),
     latest_rule_failure_time as (select created_by_id,
                                         created_date_time,
                                         row_number() over (partition by created_by_id order by created_date_time desc) as rn
                                  from rule_failure_telemetry
                                  where created_by_id in (select created_by_id from distinct_users))
select users.name,
       latest_sync_time.created_date_time as latest_sync_time,
       latest_rule_failure_time.created_date_time
from latest_sync_time
         join latest_rule_failure_time on latest_sync_time.user_id = latest_rule_failure_time.created_by_id and latest_rule_failure_time.rn = 1
         join users on users.id = latest_sync_time.user_id
where latest_sync_time.rn = 1;
```
<img width="1642" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3hGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3997fa3183111533537b1272f59a008ea88f61aa/image.png" alt="image.png" />

---
With these findings I am closing those rule failures. Let's see if they come back again.

**Comment by BEULAHEVANJALIN** [comment] 2024-04-09 12:11
```sql
set role jnpct;

select *
from rule_failure_telemetry
where rule_uuid = '26d3e45e-7174-433f-b4a7-db1524648252'
  and is_closed is false
order by last_modified_date_time desc;


update rule_failure_telemetry
set is_closed        = true,
    closed_date_time = current_timestamp
where rule_uuid = '26d3e45e-7174-433f-b4a7-db1524648252'
  and is_closed is false
  and organisation_id = 62;
```

---
Closed 73 open rule failures as part of this card.

___

**Comment by BEULAHEVANJALIN** [comment] 2024-06-13 09:49
https://avni.freshdesk.com/a/tickets/3889

**Closed as completed by BEULAHEVANJALIN** 2024-06-13 09:49 UTC
Labels: Support
