### ISSUE TITLE
Fix rule for uuid "26d3e45e-7174-433f-b4a7-db1524648252"

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/jnpct#115] opened 2024-03-25 06:15 UTC
The rule is present in the program_summary rule of the "Pregnancy" program.
On looking at the rule, there is a question called "IF YES, the result of sickle cell test" in the "ANC" form which is a non-mandatory field which is calculating "Sickle Cell Result".
Since the question is non-mandatory, when it does a getReadableValue(), it gives you an error.

- [ ] Fix the rule such that it checks if the value is defined or not and then gets the value.

**Comment by BEULAHEVANJALIN** [comment] 2024-04-10 06:45
duplicate of #117

**Closed as completed by BEULAHEVANJALIN** 2024-04-10 06:45 UTC
Labels: Support
